# Kafka (Docker / Cloud)
spring.kafka.bootstrap-servers=kafka:9093

# Production DB (later PostgreSQL)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Groq API
AI_Career_Counselling_API_Key=${GROQ_API_KEY}
groq.api.url=https://api.groq.com/openai/v1/chat/completions
groq.model=llama-3.3-70b-versatile
